config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs do
    resources :resumes
  end
  root "jobs#index"
  namespace :admin do
    resources :jobs do
      resources :resumes
      member do
        post :open
        post :close
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_down_bound, presence: true
  validates :wage_down_bound, numericality: { greater_than: 0}
  def open!
    self.is_hidden = false
    self.save
  end
  def close!
    self.is_hidden = true
    self.save
  end
  scope :published, -> { where(is_hidden: false)}
  scope :recent, -> { order('created_at DESC')}
  has_many :resumes 
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :content, presence: true
  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end
  has_many :resumes 
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :require_is_admin
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end
  def open
    @job = Job.find(params[:id])
      @job.open!
    redirect_to :back
  end
  def close
    @job = Job.find(params[:id])
      @job.close!
    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :string, :description, :wage_upper_bound, :wage_down_bound, :contact_email, :is_hidden)
  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout 'admin'
  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_is_admin
    if !current_user.admin?
     redirect_to root_path
    end 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = case params[:order]
    when 'by_down_bound'
      Job.published.order('wage_down_bound DESC')
    when 'by_upper_bound'
      Job.published.order('wage_upper_bound DESC')
    else
      Job.published.recent
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    if @job.is_hidden
      redirect_to root_path
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :string, :description, :attachment )
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end
  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user
    if @resume.save
      redirect_to job_path(@job)
    else
      render :new
    end
  end
  private
  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span,"", class: "fa fa-lock")
    else
      content_tag(:span,"", class: "fa fa-globe")
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>
<%= simple_form_for [:admin, @job] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :wage_down_bound, :label => "薪资下限" %>
  <%= f.input :wage_upper_bound, :label => "薪资上限" %>
  <%= f.input :contact_email %>
  <%= f.input :is_hidden %>
  <%= f.submit "submit"%>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("add a job", new_admin_job_path, class: "btn btn-default")%>
</div>
<br><br>
<table class="table table-bordered">
  <% @jobs.each do |job| %>
  <tr>
    <td>
      <%= render_job_status(job)%>
      <%= link_to(job.title, admin_job_path(job))%>
    </td>
    <td>
      <%= link_to(job.resumes.count, admin_job_resumes_path(job))%>
    </td>
    <td>
      <% if job.is_hidden %>
         <%= link_to("open", open_admin_job_path(job), method: :post )%>
      <% else %>
         <%= link_to("close", close_admin_job_path(job), method: :post)%>
      <% end %>
      <%= link_to("Edit", edit_admin_job_path(job))%>
      <%= link_to("Delete", admin_job_path(job), method: :delete, data: { confirm: "Are you sure?"})%>
    </td>
    <td>
      <%= job.created_at%>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/jobs/new.html.erb
<h1> add a job </h1>
<%= simple_form_for [:admin,@job] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :wage_down_bound, :label => "薪资下限" %>
  <%= f.input :wage_upper_bound, :label => "薪资上限" %>
  <%= f.input :contact_email %>
  <%= f.input :is_hidden %>
  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p>
  <%= simple_format(@job.description)%>
</p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-12">
                <h3 class="panel-title">
                  <%= resume.user.email %>
                </h3>
            </div>

        </div>
    </div>
    <div class="panel-body">
        <div class="trix-content">
            <%= simple_format(resume.content)%>
        </div>

        <hr>
        <% if resume.attachment.present? %>
         <%= link_to("Download", resume.attachment_url)%>
        <% else %>
          <p> no attachment </p>
        <% end %>


    </div>

</div>

app/views/admin/resumes/index.html.erb
<h2><%= @job.title %>履历列表</h2>
<hr>
<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Job Listing </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <% if current_user && current_user.admin? %>
                          <li> <%= link_to("admin panel", admin_jobs_path)%></li>
                        <% end %>
                        <li class="divider"></li>
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/jobs/_form.html.erb
<%= simple_form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>
<div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", jobs_path(order: "by_down_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", jobs_path(order: "by_upper_bound") ) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", jobs_path  ) %>

        </li>
    </ul>
</div>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.string %></td>
        <td><%= job.description %></td>
        <td>
          <%= job.wage_down_bound %>
        </td>
        <td>
          <%= job.wage_upper_bound %>
        </td>
        <td>
          <%= job.created_at %>
        </td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
<%= link_to("提交履历", new_job_resume_path(@job))%>

<p>
  <strong>String:</strong>
  <%= @job.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@job.description) %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Job Listing </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <div class="row">
              <div class="col-md-2">
                <ul class="nav nav-pills nav-stacked" style="max-width: 300px; padding-top:20px;">
                  <li class="active"><%= link_to("Jobs", admin_jobs_path ) %> </li>
                </ul>
              </div>

              <div class="col-md-10">
                <%= yield %>
              </div>
           </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joblisting1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/resumes/new.html.erb
<h3> 投交履历到 <%= @job.title %> </h3>

<hr>

<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content %>
  <%= f.input :attachment %>
  <%= f.submit "送出" %>
<% end %>